# Generated by Django 4.1.7 on 2023-04-06 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cart_delete_basket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
